trigger:
  branches:
    include:
      - '*'

resources:
  repositories:
  - repository: azure-pipelines-spfx-templates
    type: github
    name: manbhar/azure-pipelines-spfx-templates
    endpoint: manbhar

variables:
  - group: office365credentials
  - name: node_version
    value: '10.x'
  - name: package_manager
    value: 'npm'

steps:
  ##########################################
  ## specify which node version to use
  ##########################################
  - task: UseNode@1
    displayName: Set to Node.js 
    inputs:
      version: '10.x'
    
  ##########################################
  ## install dependencies using specified
  ##    package manager
  ##########################################
  - task: Npm@1
    inputs:
    command: 'ci'
    workingDir: 'sample' 