trigger:
  branches:
    include:
      - '*'

resources:
  repositories:
  - repository: azure-pipelines-spfx-templates
    type: github
    name: manbhar/azure-pipelines-spfx-templates
    endpoint: manbhar-github

variables:
  - group: office365credentials
  - name: node_version
    value: '10.x'
  - name: package_manager
    value: 'npm'

stages:
- stage: Build
  dependsOn: []
  jobs:
    - template: jobs/build.yml@azure-pipelines-spfx-templates
      parameters:
        working_directory: sample
        package_manager: ${{ variables.package_manager }}
        node_version: ${{ variables.node_version }}
- stage: Test
  dependsOn: []
  jobs:
    - template: jobs/test.yml@azure-pipelines-spfx-templates
      parameters:
        working_directory: sample
        package_manager: ${{ variables.package_manager }}
        node_version: ${{ variables.node_version }}