trigger:
  branches:
    include:
      - '*'

pool:
  vmImage: 'ubuntu-16.04'
  demands:
  - npm

resources:
  repositories:
  - repository: azure-pipelines-spfx-templates
    type: github
    name: manbhar/azure-pipelines-spfx-templates
    endpoint: Manish-github

variables:
  - group: office365credentials
  - name: node_version
    value: '10.x'
  - name: package_manager
    value: 'npm'
  - name: Working-directory
    value: '.'


steps:
##########################################
## specify which node version to use
##########################################
- task: UseNode@1
  inputs:

##########################################
## install npm
##########################################



##########################################
## install dependencies using npm
##########################################
- task: Npm@1
  inputs:
    command: 'ci'
    workingDir: '${{ variables.working_directory }}' 

