trigger:
- '*'

pool:
  vmImage: 'ubuntu-16.04'
  demands:
  - npm

variables:
  buildConfiguration: 'Release'

steps:
- task: Npm@1
  displayName: 'Run npm install'
  inputs:
    verbose: false

    

