trigger:
  branches:
    include:
      - '*'

pool:
  vmImage: 'ubuntu-16.04'
  demands:
  - npm

resources:
  repositories:
  - repository: azure-pipelines-spfx-templates
    type: github
    name: manbhar/azure-pipelines-spfx-templates
    endpoint: Manish-github

variables:
  working_directory: '.'
  
  


steps:
##########################################
## install dependencies using npm
##########################################
- task: Npm@1
  inputs:
    command: 'ci'
    workingDir: $(working_directory)

