trigger:
  branches:
    include:
      - '*'

resources:
  repositories:
  - repository: azure-pipelines-spfx-templates
    type: github
    name: manbhar/azure-pipelines-spfx-templates
    endpoint: Manish-github

variables:
  - group: office365credentials
  - name: node_version
    value: '10.x'
  - name: package_manager
    value: 'npm'
  - name: Working-directory
    value: '.'


steps:
##########################################
## specify which node version to use
##########################################
- task: UseNode@1
  displayName: Set to Node.js ${{ variable.node_version }}
  inputs:
  version: ${{ variables.node_version }}
  condition: ne('${{ variables.node_version }}', '')

##########################################
## install npm
##########################################



##########################################
## install dependencies using npm
##########################################
- task: Npm@1
  inputs:
    command: 'ci'
    workingDir: '${{ variables.working_directory }}' 

